### ISSUE TITLE
Artifact Hub Chart not installing correctly

### ISSUE THREAD

**Issue by huang-jy** [mjohnson9/helm#19]
I'm experimenting with this chart after finding it on artifact hub and tried installing it on a k8s v1.21 minikube and in a k8s v1.21 GKE cluster and in both cases, the pod gets stuck on `ContainerCreating` with the error:

```
  Warning  FailedMount  15s (x12 over 8m29s)  kubelet            MountVolume.SetUp failed for volume "config" : configmap "pleroma-config" not found
```

I chose not to override the default values for this experiment but the defaults seem fine, so I'm not sure where the configmap definition is.

**Comment by mjohnson9** [comment]
I ended up giving up on Pleroma and using Mastodon instead due to some issues with OIDC, so I didn’t finish this chart. Apologies.

I’m unsure why it isn’t creating a ConfigMap. It should be populating it with the contents of `config.exs` here: https://github.com/mjohnson9/helm/blob/fe0404901beca85ebdad040c75c1c54829fd184d/charts/pleroma/values.yaml#L40

**Comment by huang-jy** [comment]
No worries, I suspected it might have been abandoned. All good :+1:
